version: '2'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  backend:
    image : kaicloud34813/mpp_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    image : kaicloud34813/mpp_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
